import {
  SiReact,
  SiNodedotjs,
  SiTypescript,
  SiNextdotjs,
  SiGraphql,
  SiTailwindcss,
  SiShadcnui,
  SiFirebase,
  SiGoogleanalytics,
  SiFigma,
  SiJest,
  SiCypress,
  SiDocker,
  SiStorybook,
  SiExpress,
  SiHtml5,
  SiCss3,
  SiStyledcomponents,
  SiDaisyui,
  SiJavascript,
} from "react-icons/si";

export const ICONS = {
  react: SiReact,
  nodejs: SiNodedotjs,
  typescript: SiTypescript,
  nextjs: SiNextdotjs,
  graphql: SiGraphql,
  tailwind: SiTailwindcss,
  shadcn: SiShadcnui,
  firebase: SiFirebase,
  analytics: SiGoogleanalytics,
  figma: SiFigma,
  jest: SiJest,
  cypress: SiCypress,
  docker: SiDocker,
  storybook: SiStorybook,
  express: SiExpress,
  css: SiCss3,
  html: SiHtml5,
  styled: SiStyledcomponents,
  daisy: SiDaisyui,
  javascript: SiJavascript
} as const;
