export const SKILLS = [
  {
    name: "React",
    icon: "react",
    style: "text-blue-600 hover:shadow-blue-600",
    description: "Building interactive UIs",
  },
  {
    name: "Next.js",
    icon: "nextjs",
    style: "text-gray-500 hover:shadow-gray-500",
    description: "React framework for production",
  },
  {
    name: "TypeScript",
    icon: "typescript",
    style: "text-blue-600 hover:shadow-blue-600",
    description: "Type-safe JavaScript",
  },
  {
    name: "Node.js",
    icon: "nodejs",
    style: "text-green-700 hover:shadow-green-700",
    description: "Server-side JavaScript",
  },
  {
    name: "Express",
    icon: "express",
    style: "text-gray-600 hover:shadow-gray-600",
    description: "Minimalist web framework for Node.js",
  },
  {
    name: "GraphQL",
    icon: "graphql",
    style: "text-pink-600 hover:shadow-pink-600",
    description: "Efficient API queries and schema-based data fetching",
  },
  {
    name: "Firebase",
    icon: "firebase",
    style: "text-yellow-500 hover:shadow-yellow-500",
    description: "Backend-as-a-Service for app development",
  },
  {
    name: "Docker",
    icon: "docker",
    style: "text-blue-600 hover:shadow-blue-600",
    description: "Containerization for scalable applications",
  },
  {
    name: "TailwindCSS",
    icon: "tailwind",
    style: "text-teal-500 hover:shadow-teal-500",
    description: "Utility-first CSS framework for styling",
  },
  {
    name: "Shadcn UI",
    icon: "shadcn",
    style: "text-indigo-500 hover:shadow-indigo-500",
    description: "Customizable UI components for React",
  },
  {
    name: "Jest",
    icon: "jest",
    style: "text-pink-600 hover:shadow-pink-600",
    description: "JavaScript testing framework",
  },
  {
    name: "Cypress",
    icon: "cypress",
    style: "text-cyan-500 hover:shadow-cyan-500",
    description: "End-to-end testing for web applications",
  },
  {
    name: "Storybook",
    icon: "storybook",
    style: "text-indigo-600 hover:shadow-indigo-600",
    description: "UI component development environment",
  },
  {
    name: "Figma",
    icon: "figma",
    style: "text-purple-600 hover:shadow-purple-600",
    description: "Design and prototyping tool for interfaces",
  },
  {
    name: "Google Analytics",
    icon: "analytics",
    style: "text-yellow-500 hover:shadow-yellow-500",
    description: "Web analytics for user behavior insights",
  },
  {
    name: "JavaScript",
    icon: "javascript",
    style: "text-yellow-500 hover:shadow-yellow-500",
    description: "Dynamic and versatile programming language",
  },
  {
    name: "HTML 5",
    icon: "html",
    style: "text-orange-600 hover:shadow-orange-600",
    description: "Structure and content for the web",
  },
  {
    name: "CSS 3",
    icon: "css",
    style: "text-blue-500 hover:shadow-blue-500",
    description: "Styling and layout for web applications",
  },
  {
    name: "Daisy UI",
    icon: "daisy",
    style: "text-green-500 hover:shadow-green-500",
    description: "Tailwind CSS-based component library",
  },
  {
    name: "Styled Components",
    icon: "styled",
    style: "text-pink-500 hover:shadow-pink-500",
    description: "CSS-in-JS library for styling React components",
  },
  {
    name: "React Native CLI",
    icon: "react",
    style: "text-blue-400 hover:shadow-blue-400",
    description: "Build native mobile apps with React",
  },
];